server:
  port: 8080
  tomcat:    
    file-encoding: UTF-8    
  servlet:
    jsp:
      init-parameters: 
        development: true 
    session:
      timeout: 7200
  error:
    whitelabel:
      enabled: false
   
spring: 
  mvc: 
    view:  
      prefix: /WEB-INF/views/
      suffix: .jsp